version: '2'

services:
    mongo:
        image: mongo:3.4.0
        restart: on-failure
        volumes:
            - ./data/db:/data/db
        command: mongod --smallfiles --oplogSize 128

    api:
        build: ./api
        restart: on-failure
        depends_on:
            - mongo
        links:
            - mongo

    rocketchat:
        image: rocketchat/rocket.chat:latest
        restart: on-failure
        environment:
            - PORT=3000
            - MONGO_URL=mongodb://mongo:27017/rocketchat
        links:
            - mongo
        ports:
            - 3000:3000

    bot:
        build: ./bot
        restart: on-failure
        links:
            - api
